### PR TITLE
Fixes 2 - 536 tests passing :)

### PR DESCRIPTION
**Pull request by albertjan**
This contains everything from fixes 1 plus the ast_for_call stuff. I'm unsure how to continue here.

### CODE REVIEW

**Comment by albertjan** [comment]
I was attempting to fix test 282

**Comment by albertjan** [comment]
fixed test 282 *args and varargs now work.

**Comment by albertjan** [comment]
💃

**Comment by albertjan** [comment]
Ok 5 more tests pass I did the throw exception bit 😄

**Comment by albertjan** [comment]
💃

**Comment by albertjan** [comment]
image

**Comment by albertjan** [comment]
With fixing one thing I may have made it harder to make ast.js do the correct thing. If you're attacking this it might be handy to undo those grammar changes and do the ast and then redo the grammar changes and make the ast understand both.

**Comment by meredydd** [comment]
Rebased and merged.

**Pull request closed without merging**
